name: tracer-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.9
  - arm_pyart
  - matplotlib
  - hvplot
  - jupyterlab
  - holoviews
  - geoviews
  - cartopy
  - numpy
  - dask
  - distributed
  - pandas
  - datashader
  - geopandas
  - pip
  - pip:
      - s3fs
      - nexradaws
      - git+https://github.com/pydata/xarray

